### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by JamieIrvine** [MichaelJohnWatters/MichaelJohnWatters.github.io#1]
Hi, I don't seem to have permission to push to this repository, can you take a look?

`fatal: Authentication failed for 'https://github.com/MichaelJohnWatters/MichaelJohnWatters.github.io.git/'`

**Comment by MichaelJohnWatters** [comment]
:suspect:

**Comment by MichaelJohnWatters** [comment]
no
